import { spotsLeft, type EventState } from "./chain";
import { fromStroops } from "./contracts";
import { formatXlm } from "./format";

/**
 * What a Showup link looks like when it is pasted somewhere.
 *
 * The invite link is the product's only distribution mechanism: an organizer
 * creates an event and sends `/e/<address>` to a group chat. Without any of
 * this, that message renders as a bare URL ending in fifty-six characters of
 * base32 — which is indistinguishable, to a guest who has never heard of this,
 * from the kind of link you are told never to open. The deposit mechanic asks
 * people to lock money on the strength of that first impression.
 *
 * So the preview says what the event is, what it costs, and whether there is
 * still room, read from the chain at request time.
 */

export const SITE_NAME = "Showup";
export const SITE_TITLE = "Showup — on-chain anti-flake deposits";
export const SITE_DESCRIPTION =
  "Put a refundable deposit on showing up. Reserve, check in, reclaim — on Stellar Testnet.";

/** The title shown when the chain read fails, or for an event with no name. */
export const UNTITLED = "Untitled event";

/**
 * The card generated by `app/opengraph-image.tsx`, named by hand.
 *
 * Next attaches that file to every route automatically — but only while the
 * route says nothing about `openGraph` itself. `/e/[id]` has to, because the
 * whole point is a per-event title, and declaring the field replaces the
 * inherited one wholesale rather than merging into it. Left implicit, the one
 * link anybody actually shares was the only link with no image on it.
 */
export const OG_IMAGE_PATH = "/opengraph-image";

export type Preview = { title: string; description: string };

function depositPhrase(event: EventState): string {
  return `${formatXlm(fromStroops(event.deposit))} XLM deposit`;
}

/**
 * Deliberately no date or time.
 *
 * This string is built on a server — UTC on Vercel — while the page itself
 * formats `startsAt` in whatever zone the reader's browser is in. Putting a
 * clock time in here means the preview and the page disagree by three hours
 * for every Turkish guest, and the preview is the one they read first. Every
 * other fact here is timezone-free, so the whole line is safe to trust.
 */
export function eventPreview(event: EventState): Preview {
  const title = `${event.title.trim() || UNTITLED} · ${SITE_NAME}`;
  const deposit = depositPhrase(event);

  if (event.phase === "Finalized") {
    return {
      title,
      description: `${deposit} · settled — ${event.checkedIn.length} of ${event.reserved.length} showed up.`,
    };
  }

  if (event.phase === "CheckingIn") {
    return {
      title,
      description: `${deposit} · check-in is open. Guests who show up get their deposit back.`,
    };
  }

  const left = spotsLeft(event);
  if (left <= 0) {
    return {
      title,
      description: `${deposit} · full, all ${event.capacity} spots reserved.`,
    };
  }

  return {
    title,
    description: `${deposit} · ${left} of ${event.capacity} ${
      left === 1 ? "spot" : "spots"
    } left. Reserve yours and get it back when you show up.`,
  };
}

/**
 * The preview for an address the chain could not be asked about.
 *
 * Reached when RPC is slow or down, and — far more often — when someone opens a
 * link to an address that never held an event. It must not claim the event is
 * missing: `generateMetadata` gets one shot at a possibly-flaky read, whereas
 * the page underneath retries and can tell the two apart properly. Saying
 * nothing specific is the only claim that is true in both cases.
 */
export const FALLBACK_PREVIEW: Preview = {
  title: `Event · ${SITE_NAME}`,
  description: SITE_DESCRIPTION,
};
